name: Alert Teams

on:
  push:
    branches: ["main"]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Teams
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{
            "text": "Novo commit na main pelo autor ${{ github.actor }}"
          }' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}
